Repository ember-cli/broccoli-babel-transpiler, pull requests merged in 2018-12, with the labels that each got.

#157 TravisCI: Remove deprecated `sudo: false` option
  .travis.yml
Labels: internal

#151 Update README.md
  README.md
Labels: documentation

#159 parallel-api: Fix "Cannot read property '_parallelBabel' of null" error
  lib/parallel-api.js
  tests/test.js
Labels: bug

#160 Add Changelog
  CHANGELOG.md
  package.json
  yarn.lock
Labels: documentation
