Repository ember-cli/broccoli-babel-transpiler, pull requests merged in 2020-10, with the labels that each got.

#191 Remove browserPolyfill option
  README.md
  index.js
  tests/test.js
Labels: breaking

#193 Separate Broccoli and Babel options
  README.md
  index.js
  lib/options-hash.js
  lib/parallel-api.js
  tests/test-slow.js
  tests/test.js
Labels: breaking

#190 Update `workerpool` to latest (avoiding deprecations)
  lib/parallel-api.js
  package.json
  yarn.lock
Labels: enhancement

#194 Update to `@babel/core@7.12.0`.
  package.json
  yarn.lock
Labels: enhancement

#183 Add GitHub Actions CI setup.
  .gitattributes
  .github/workflows/ci.yml
Labels: internal

#195 Remove TravisCI and AppVeyor
  .travis.yml
  appveyor.yml
Labels: internal
