Repository ember-cli/broccoli-babel-transpiler, pull requests merged in 2022-10, with the labels that each got.

#221 [BREAKING] Move `@babel/core` to `peerDependencies` to resolve peer dependency warnings and errors
  package-lock.json
  package.json
Labels: breaking

#226 Add release automation
  CHANGELOG.md
  RELEASE.md
  package-lock.json
  package.json
Labels: internal

#230 Fix typo in docs
  README.md
Labels: documentation
